title: fractal.fish
markdown: kramdown

baseurl: ""
url: "https://fractal.fish"

permalink: /:year/:month/:day/:title/


collections:
  text:
    output: true
  code:
    output: true
  pixels:
    output: true




